Repository Jungle-Works/AllSpark, pull requests merged in 2018-04, with the labels that each got.

#135 Feature/string x axis
  client/css/dashboard.css
  client/css/main.css
  client/css/reports.css
  client/index.js
  client/js/connections.js
  client/js/dashboard.js
  client/js/dashboards.js
  client/js/main.js
  client/js/reports.js
  server/app.js
  server/www/authentication.js
  server/www/credentials.js
  server/www/users.js
Labels: enhancement

#140 Added global filter names, non filtered reports are now more transpar…
  client/css/dashboard.css
  client/css/main.css
  client/css/reports.css
  client/index.js
  client/js/dashboard.js
  client/js/main.js
  client/js/reports.js
  server/package.json
  server/www/datasets.js
Labels: bug, enhancement

#146 Feature/filters multiple
  client/css/dashboard.css
  client/css/main.css
  client/js/dashboard.js
  client/js/main.js
  server/www/datasets.js
  server/www/reports/engine.js
  server/www/users.js
Labels: Front End, enhancement

#159 theme
  client/css/dashboard.css
  client/css/main.css
Labels: Front End

#172 engine v2 initial commit
  server/utils/api.js
  server/utils/constants.js
  server/utils/pgsql.js
  server/www/datasets.js
  server/www/reports/engine.js
  server/www/reports/engine_old.js
  server/www/roles.js
Labels: Back End, enhancement

#165 Dataset ui
  client/css/settings.css
  client/index.js
  client/js/settings.js
Labels: Front End, enhancement

#177 common instances initial commit #176
  .gitignore
  README.md
  app.js
  bin/www
  client/.gitignore
  client/css/main.css
  client/index.js
  client/js/main.js
  client/package.json
  package.json
  server/.gitignore
  server/bin/www
  server/server.iml
  server/utils/mysql.js
  server/www/reports/engine.js
  views/error.jade
  views/index.jade
  views/layout.jade
Labels: Back End, Front End, enhancement

#164 Fix/drilldown features
  client/css/main.css
  client/js/main.js
  server/www/datasets.js
Labels: Front End, enhancement

#182 Added border to columns
  client/css/main.css
Labels: Front End

#194 Feature/visualization options
  README.md
  client/.htaccess
  client/css/dark.css
  client/css/dashboard.css
  client/css/main.css
  client/css/reports.css
  client/css/settings.css
  client/index.js
  client/js/dashboard.js
  client/js/main.js
  client/js/reports.js
  client/js/settings.js
  server/www/reports/report.js
Labels: Front End

#209 Fixed drilldown form default values, UI and table UI
  client/css/dark.css
  client/css/dashboard.css
  client/css/main.css
  client/css/reports.css
  client/index.js
  client/js/dashboard.js
  client/js/main.js
  client/js/reports.js
Labels: Front End, enhancement

#226 Hotfix/misc
  client/css/dashboard.css
  client/css/main.css
  client/css/reports.css
  client/index.js
  client/js/dashboard.js
  client/js/main.js
  client/js/reports.js
Labels: Enhancement, Front End
